-- ja 模式的少量日文汉字补充表。
-- 键是去掉 ja 前缀后的罗马字；值按候选顺序排列。
-- 这里只收录中文输入和拆字反查都不方便、但确实需要的字符或短词。

return {
    akatsuki = { "暁" },
    aoi = { "葵" },
    azusa = { "梓" },
    eki = { "駅" },
    en = { "円" },
    ha = { "歯" },
    hama = { "浜" },
    hatake = { "畑" },
    hatsu = { "発" },
    hiiragi = { "柊" },
    hime = { "姫" },
    hotaru = { "蛍" },
    kaede = { "楓" },
    kaoru = { "薫" },
    kari = { "仮" },
    kame = { "亀" },
    ki = { "気" },
    kuro = { "黒" },
    mio = { "澪" },
    momiji = { "椛" },
    nagi = { "凪" },
    nagisa = { "渚" },
    rin = { "凛" },
    ryuu = { "竜" },
    sakaki = { "榊" },
    saki = { "咲" },
    sakura = { "桜" },
    sawa = { "沢" },
    shio = { "塩" },
    shiori = { "栞" },
    shizuku = { "雫" },
    sumire = { "菫" },
    tako = { "凧" },
    taki = { "滝" },
    tetsu = { "鉄" },
    touge = { "峠" },
    tsubaki = { "椿" },
    tsuji = { "辻" },
    zu = { "図" },
}
